---
title: "Nex_Go_morphometrics"
output: html_document
date: "2023-12-30"
---

```{r setup libraries, include=FALSE}
library(stringr)
library(readr)
library(geomorph)
library(gplots)
library(ggplot2)
library(borealis)
library(readr)
library(ggstatsplot)
```

```{r 1 -> Prepare input for MorphoJ check, echo=FALSE}
#Go load 12 necessary folders with csv files


 <- read_csv("~/Desktop/morphometrics/microscopy_data/annotated_files/")
 <- read_csv("~/Desktop/morphometrics/microscopy_data/annotated_files/")
 ...
 
# assign each file its condition prior to merging them in one. Nice loop would be handy here.

#merge all 12
complete = rbind(phen1108_B2_R12,phen1808_B1_R1,phen2308_B1_R4)
complete$symetry = ifelse(str_detect(complete$id, "R"), print("R"), print("L"))
complete$id = paste(complete$id, complete$condition, complete$symetry, sep = "_")

complete$id = ifelse(le)
write.table(complete, "NEX_morphometrics_Go.txt", quote = F)
#The output must be first checked with morphoJ for swaped landmarks.
#Outlier images can also be removed later in Geomorph.
```

```{r 2 -> Read output of MorphoJ and annotate it for geomorph, echo=FALSE}
NEX_wings = read_csv("~/NEX_morphoJ_final_output.txt")

fw.links <- matrix(c(1,7, 7,12, 12,13, 13,14, 14,15, 4,5, 8,9, 10,11, 8,9, 15,11, 5,11, 3,5, 3,9, 
                     6,8, 2,7, 6,12, 8,13, 10,14, 9,10, 12,7, 2,6 ),
                   ncol = 2, byrow = TRUE)

#data prep
NEX_wings$symetry = ifelse(str_detect(NEX_wings$id, "R"), print("R"), print("L"))
NEX_wings$ind = str_split_i(NEX_wings$id, "_",3)
NEX_wings$diet = str_split_i(NEX_wings$id, "_",1)
NEX_wings$condition = paste(NEX_wings$diet ,str_split_i(NEX_wings$id, "_",2), sep = "_")

NEX_wings$pair = stringr::str_extract(NEX_wings$ind, "^.{3}")
#NEX_wings$pair = paste(NEX_wings$condition, NEX_wings$pair, sep = "_")
length(unique(NEX_wings$pair))
dim(NEX_wings)

cord <- as.matrix(NEX_wings[,2:31])
shape <- arrayspecs(cord, 15, 2)
#shape_fix = estimate.missing(shape)
```

```{r 3 -> Geomorph analysis: PCA, echo=FALSE}
myGPA<-gpagen(shape) #first we perform gpa, then we rotate.
shapes_aligned <- align.reflect(myGPA, top.pt = 7, links = fw.links,provenance = NULL )

#clearly assign metadata
myGPA$condition = NEX_wings$condition
myGPA$ids = NEX_wings$id
myGPA$symetry = NEX_wings$symetry
myGPA$pairs = NEX_wings$pair
NEX_wings$condition=  ifelse(NEX_wings$condition == "ctrl_ns", paste("Control diet + no selection"), NEX_wings$condition )
NEX_wings$condition=  ifelse(NEX_wings$condition == "ctrl_fs", paste("Control diet + flight selection"), NEX_wings$condition )
NEX_wings$condition=  ifelse(NEX_wings$condition == "hgSg_ns", paste("High Sugar diet + no selection"), NEX_wings$condition )
NEX_wings$condition=  ifelse(NEX_wings$condition == "hgSg_fs", paste("High Sugar diet + flight selection"), NEX_wings$condition )
myGPA$Cond_full = NEX_wings$condition

#perform generic PCA
wing.pca <- gm.prcomp(shapes_aligned$coords)
wing.pca$condition = NEX_wings$condition
plot(wing.pca, col = as.factor(NEX_wings$condition))
ggGMMplot(wing.pca, group = NEX_wings$condition, 
          group.title = 'Condition', 
          convex.hulls = TRUE, include.legend = TRUE, label.groups = F)
m = mshape(shapes_aligned$coords)
shape.space(wing.pca, group = NEX_wings$condition, 
            group.title = 'Condition', convex.hulls = T,
            backtransform.examples = TRUE,
            ref.shape = m,
            shape.method = "points",
            bt.shape.mag = 4,
            bt.links = fw.links,pt.size = 1, label.groups = F)

```

```{r 4 -> Symetry analysis, echo=FALSE}
bs = bilat.symmetry(shapes_aligned$coords, ind = shapes_aligned$pairs, side =  shapes_aligned$symetry) #check if object.sym=T is required, my understanding is that its only necessery for radially symetrical images, or if two wings were present in the same file.

#extract and plot sizes
sizes_per_group = as.data.frame(myGPA$Csize, myGPA$Cond_full)
sizes_per_group$Cond_full  = rownames(sizes_per_group)
sizes_per_group$size = sizes_per_group$`myGPA$Csize`
ggplot(sizes_per_group, aes(x=sizes_per_group$`myGPA$Csize`, fill = Cond_full)) + geom_density(alpha = 0.6, position = "identity", bins = 30) + theme_minimal() + xlab("Wing size distribution per group")
sizes_per_group$logsize=  log10(sizes_per_group$size)
ggbetweenstats(
  data  = sizes_per_group,
  x     = Cond_full,
  y     = logsize,
  title = "Wing size distribution per group", pairwise.display = "significant", centrality.plotting = F, p.adjust.method = "bonferroni",xlab = "Groups",results.subtitle = FALSE, ylab = "Log 10 -Wing Centrod Size", palette = "Accent")

#extract and plot asymetry index
symetry_per_group = as.data.frame(bs$signed.AI, bs$condition)
symetry_per_group$CONDITION  = rownames(symetry_per_group)
symetry_per_group$CONDITION = stringr::str_extract(symetry_per_group$CONDITION, "^.{10}")
symetry_per_group = na.omit(symetry_per_group)
symetry_per_group$CONDITION =  ifelse(symetry_per_group$CONDITION == "indctrl_ns", paste("Control diet + no selection"), symetry_per_group$CONDITION )
symetry_per_group$CONDITION =  ifelse(symetry_per_group$CONDITION == "indctrl_fs", paste("Control diet + flight selection"), symetry_per_group$CONDITION )
symetry_per_group$CONDITION =  ifelse(symetry_per_group$CONDITION == "indhgSg_ns", paste("High Sugar diet + no selection"), symetry_per_group$CONDITION )
symetry_per_group$CONDITION =  ifelse(symetry_per_group$CONDITION == "indhgSg_fs", paste("High Sugar diet + flight selection"), symetry_per_group$CONDITION )
symetry_per_group$AI = symetry_per_group$`bs$signed.AI`
ggplot(symetry_per_group, aes(x=symetry_per_group$`bs$signed.AI`, fill = CONDITION)) + geom_histogram(alpha = 0.7, position = "identity", bins = 30) + theme_minimal()
ggbetweenstats(
  data  = symetry_per_group,
  x     = CONDITION,
  y     = AI,
  title = "Wing symetry index distribution per group", centrality.plotting = F, p.adjust.method = "bonferroni",xlab = "Groups", ylab = "Symetry Index",results.subtitle = FALSE, palette = "Accent")
```

```{r 5 -> Regressions: average differences between groups, echo=FALSE}
```

```{r 6 -> Regressions: flight vs. symetry/size/shape , echo=FALSE}
```

